events {
  worker_connections 1024;
}

http {
  # TODO: remplacer homeez.fr par le vrai nom de domaine dans tout ce fichier
  # Redirect HTTP → HTTPS
  server {
    listen 80;
    server_name homeez.fr www.homeez.fr api.homeez.fr;
    return 301 https://$host$request_uri;
  }

  # Front
  server {
    listen 443 ssl;
    server_name homeez.fr www.homeez.fr;

    ssl_certificate /etc/letsencrypt/live/homeez.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/homeez.fr/privkey.pem;

    location / {
      proxy_pass http://front:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }

  # Back
  server {
    listen 443 ssl;
    server_name api.homeez.fr;

    ssl_certificate /etc/letsencrypt/live/homeez.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/homeez.fr/privkey.pem;

    location / {
      proxy_pass http://back:3001;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # WebSocket
    location /socket.io {
      proxy_pass http://back:3001;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    # SSE
    location /chores/stream {
      proxy_pass http://back:3001;
      proxy_set_header Connection '';
      proxy_http_version 1.1;
      proxy_buffering off;
      proxy_cache off;
      chunked_transfer_encoding on;
    }

    location /events/stream {
      proxy_pass http://back:3001;
      proxy_set_header Connection '';
      proxy_http_version 1.1;
      proxy_buffering off;
      proxy_cache off;
      chunked_transfer_encoding on;
    }
  }
}